name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'   # or 3.10/3.9 to match your project
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # If you RENAME the file to repo root as "requirements.txt", change the next line accordingly
          pip install -r requirement/requirements.txt

      - name: Train Model
        run: |
          python model/train.py

      - name: Evaluate Model
        run: |
          python model/evaluate.py

      - name: Run Unit Tests
        run: |
          python -m unittest discover -s tests -p "test_*.py"

      - name: Deploy to Render
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
        run: |
          curl -fsSL -X POST "https://api.render.com/v1/services/${RENDER_SERVICE_ID}/deploys" \
            -H "Accept: application/json" \
            -H "Authorization: Bearer ${RENDER_API_KEY}" \
            -H "Content-Type: application/json" \
            -d '{}'
