name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'   # change to '3.8' if your libs require it

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirement.txt

    - name: Train Model
      run: |
        python model/train.py

    - name: Evaluate Model
      run: |
        python model/evaluate.py

    - name: Run Unit Tests
      run: |
        python -m unittest discover -s tests -p "test_*.py"

    - name: Deploy to Render
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      env:
        RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
      run: |
        curl -fsSL -X POST "https://api.render.com/v1/services/${RENDER_SERVICE_ID}/deploys" \
          -H "Accept: application/json" \
          -H "Authorization: Bearer ${RENDER_API_KEY}" \
          -H "Content-Type: application/json" \
          -d '{}'
